###
### AntiPieRay Main Configuration File
### by Orbyfied 2023
###

# The checked block entities by Minecraft
# namespaced key.
checked-block-entities:
  - minecraft:ender_chest
  - minecraft:banner
  - minecraft:beacon
  - minecraft:barrel
  - minecraft:enchanting_table

# The distance in which to always permit the
# block entity packets. Set to 0 to ignore this
# check.
always-view-distance: 20.0