###
### AntiPieRay Main Configuration File
### by Orbyfied 2023
###

# The block entities to be checked, listed by
# Minecraft namespaced key/identifier.
checked-block-entities:
  - minecraft:ender_chest
  - minecraft:banner
  - minecraft:beacon
  - minecraft:barrel
  - minecraft:enchanting_table

# The distance a checked tile entity has to lie within to
# be sent regardless of obstruction.
always-view-distance: 5.0