# properties
name: AntiPieRay
version: 1.0.0
main: net.orbyfied.antipieray.AntiPieRay
description: Attempts to prevent the usage of the PieRay exploit to find bases.
api-version: 1.19

# libraries
libraries:
  - net.orbyfied.j8:j8-util:0.2.2.1

# commands
commands:
  antipieray:
    description: AntiPieRay main command